import { AgentProfile } from '@/types'

export function generateAgentMd(profile: AgentProfile): string {
  const createdDate = profile.createdAt instanceof Date
    ? profile.createdAt.toLocaleDateString()
    : new Date(profile.createdAt).toLocaleDateString()

  return `# ${profile.name || 'My AI Agent'}

> Generated by [agent-me.app](https://agent-me.app) on ${createdDate}

## Overview

This AI agent is designed to communicate and think like you. It captures your unique personality, work style, and communication patterns to serve as your digital twin.

## Personality Profile

### Communication Style
- **Style:** ${capitalize(profile.personality.communicationStyle)}
- **Verbosity:** ${capitalize(profile.personality.verbosity)}
- **Tone:** ${capitalize(profile.personality.tone)}
- **Decision Making:** ${capitalize(profile.personality.decisionMaking)}

### Work Style
- **Problem Solving:** ${capitalize(profile.workStyle.problemSolvingApproach)}
- **Learning Style:** ${capitalize(profile.workStyle.learningStyle)}
${profile.workStyle.preferredTools.length > 0 ? `- **Preferred Tools:** ${profile.workStyle.preferredTools.join(', ')}` : ''}

### Communication Patterns
- **Message Length:** ${capitalize(profile.communication.averageMessageLength)}
- **Uses Emojis:** ${profile.communication.usesEmojis ? 'Yes' : 'No'}
- **Uses Code Examples:** ${profile.communication.usesCodeExamples ? 'Yes' : 'No'}
- **Asks Clarifying Questions:** ${profile.communication.asksClarifyingQuestions ? 'Yes' : 'No'}
- **Provides Context:** ${profile.communication.providesContext ? 'Yes' : 'No'}

## Areas of Focus

${profile.interests.primaryTopics.map(topic => `- ${topic}`).join('\n')}

## Goals & Motivations

${profile.interests.goalsAndMotivations.map(goal => `- ${goal}`).join('\n') || '- Excellence in chosen field'}

## How to Use This Agent

### Option 1: ChatGPT Custom Instructions
1. Go to ChatGPT → Settings → Personalization → Custom Instructions
2. Paste the system prompt from \`SYSTEM_PROMPT.md\` into "How would you like ChatGPT to respond?"

### Option 2: Claude Projects
1. Create a new Project in Claude
2. Add the system prompt to the Project Instructions

### Option 3: API Integration
Use the system prompt as the \`system\` message when calling OpenAI, Anthropic, or other LLM APIs.

\`\`\`python
# Example with OpenAI
from openai import OpenAI
client = OpenAI()

with open('SYSTEM_PROMPT.md', 'r') as f:
    system_prompt = f.read()

response = client.chat.completions.create(
    model="gpt-4",
    messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": "Your message here"}
    ]
)
\`\`\`

## Analysis Stats

${profile.analysis.totalMessages > 0 ? `- **Messages Analyzed:** ${profile.analysis.totalMessages.toLocaleString()}` : ''}
${profile.analysis.totalConversations > 0 ? `- **Conversations Analyzed:** ${profile.analysis.totalConversations.toLocaleString()}` : ''}
${profile.analysis.topKeywords.length > 0 ? `- **Top Keywords:** ${profile.analysis.topKeywords.slice(0, 10).join(', ')}` : ''}

---

*This agent profile was generated by analyzing your communication patterns and preferences. The more data provided, the more accurate the representation.*
`
}

export function generateSkillsMd(profile: AgentProfile): string {
  const technicalSkills = profile.workStyle.preferredTools || []
  const topics = profile.interests.primaryTopics || []
  const expertise = profile.workStyle.expertise || []

  return `# Skills & Capabilities

> AI Agent Skills Profile

## Core Competencies

### Primary Expertise
${expertise.length > 0 ? expertise.map(e => `- ${e}`).join('\n') : '- General assistance and problem-solving'}

### Knowledge Domains
${topics.map(topic => `- ${topic}`).join('\n') || '- General knowledge'}

## Technical Skills

${technicalSkills.length > 0 ? technicalSkills.map(skill => `### ${skill}
- Proficient in ${skill} concepts and best practices
- Can assist with ${skill}-related questions and tasks
`).join('\n') : `### General Technical Assistance
- Can help with various technical topics
- Provides guidance based on best practices
`}

## Communication Capabilities

### Strengths
${profile.personality.communicationStyle === 'technical' ? '- Technical explanations and documentation' : ''}
${profile.personality.communicationStyle === 'casual' ? '- Friendly, approachable interactions' : ''}
${profile.personality.communicationStyle === 'formal' ? '- Professional, structured communication' : ''}
${profile.personality.verbosity === 'detailed' ? '- Comprehensive, thorough responses' : ''}
${profile.personality.verbosity === 'concise' ? '- Quick, to-the-point answers' : ''}
${profile.communication.usesCodeExamples ? '- Code examples and technical demonstrations' : ''}
${profile.communication.asksClarifyingQuestions ? '- Asking clarifying questions for accuracy' : ''}
- Adapting to user needs and context

### Problem-Solving Approach
${getProblemSolvingDescription(profile.workStyle.problemSolvingApproach)}

## Best Used For

${generateUseCases(profile)}

## Limitations

- Knowledge based on training data and provided context
- Cannot access external systems or real-time information
- Should verify critical information independently
- Works best when given clear context and requirements

## Integration Options

| Platform | Method |
|----------|--------|
| ChatGPT | Custom Instructions |
| Claude | Project Instructions |
| OpenAI API | System message |
| Anthropic API | System prompt |
| LangChain | System message in chain |
| Custom Apps | Include in prompt template |

---

*Skills are derived from analyzed communication patterns and stated preferences.*
`
}

export function generateSystemPromptMd(profile: AgentProfile): string {
  return `# System Prompt

> Use this prompt to configure AI assistants to behave like your agent.

---

${profile.systemPrompt}

---

## Usage Instructions

### ChatGPT
1. Go to Settings → Personalization → Custom Instructions
2. Paste the above prompt into "How would you like ChatGPT to respond?"

### Claude
1. Start a new conversation
2. Paste the prompt as your first message, or
3. Create a Project and add it to Project Instructions

### API Usage

\`\`\`javascript
// OpenAI
const response = await openai.chat.completions.create({
  model: "gpt-4",
  messages: [
    { role: "system", content: systemPrompt },
    { role: "user", content: userMessage }
  ]
});

// Anthropic
const response = await anthropic.messages.create({
  model: "claude-3-opus-20240229",
  system: systemPrompt,
  messages: [{ role: "user", content: userMessage }]
});
\`\`\`
`
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1).replace(/_/g, ' ')
}

function getProblemSolvingDescription(approach: string): string {
  const descriptions: Record<string, string> = {
    systematic: `- Breaks down complex problems into manageable steps
- Follows logical, structured approaches
- Documents process and reasoning`,
    creative: `- Explores unconventional solutions
- Thinks outside the box
- Generates multiple alternative approaches`,
    collaborative: `- Seeks input and feedback
- Builds on others' ideas
- Facilitates group problem-solving`,
    independent: `- Works through challenges autonomously
- Self-directed research and learning
- Delivers complete solutions`,
  }
  return descriptions[approach] || descriptions.systematic
}

function generateUseCases(profile: AgentProfile): string {
  const useCases: string[] = []

  if (profile.communication.usesCodeExamples) {
    useCases.push('- Code review and technical discussions')
    useCases.push('- Debugging and troubleshooting')
  }

  if (profile.personality.verbosity === 'detailed') {
    useCases.push('- In-depth explanations and documentation')
    useCases.push('- Comprehensive analysis and reports')
  }

  if (profile.personality.verbosity === 'concise') {
    useCases.push('- Quick answers and summaries')
    useCases.push('- Rapid decision support')
  }

  if (profile.personality.communicationStyle === 'technical') {
    useCases.push('- Technical writing and documentation')
    useCases.push('- Architecture and design discussions')
  }

  if (profile.workStyle.problemSolvingApproach === 'creative') {
    useCases.push('- Brainstorming and ideation')
    useCases.push('- Creative problem-solving')
  }

  profile.interests.primaryTopics.forEach(topic => {
    useCases.push(`- ${topic} related tasks and questions`)
  })

  return useCases.slice(0, 8).join('\n') || '- General assistance and conversation'
}
